### ISSUE TITLE
Some notes after a quick try

### ISSUE THREAD

**Issue by jpcima** [farvardin/binaural-synth#1]
Hello,
I have played a little with binaural-synth and looked a bit how it was made.
(or more precisely, in the reverse order :wink:)

It works good, I share some quick remarks.

- the `noise cutoff` ("cuff off" ?) is unbounded, and probably it should be kept in MIDI range.
by some manipulation of this control, I was apparently able to kill the filter which silenced the noise section. 
It's not so surprising as raising the value (semitone) will increase the frequency to very high values.
(probably it should be also capped to nyquist or a little below)

- the `cents` value is not really indicating cents (neither of Hz or semitone)

**Comment by farvardin** [comment]
Thank you for the feedback. I've corrected the misspell for cut off, and I've also added boundaries to avoid the problem you've encountered. I put an upper limit of 140, which correspond to around 26000 hz, it should be enough to get interesting noise effects without getting the filter completely crazy.

I've removed to "cent" label, and also divided by 100 instead of 10, so now it means 4 Hz 850 = 4.85 Hz
